const mongoose = require("mongoose");

const pushNotificationModelSchema = new mongoose.Schema(
  {
    object_id: mongoose.Schema.Types.ObjectId, // Automatically generated by MongoDB
    notification_title: {
      type: String,
      required: true,
    },
    notification_desc: {
      type: String,
      required: true,
    },
    created_by: {
      type: mongoose.Schema.Types.ObjectId, // Here will be add the admin id who create this obj
      ref: "User",
      required: true,
    },
  },
  { timestamps: true, versionKey: false }
);

const PushNotificationModel = mongoose.model(
  "PushNotification",
  pushNotificationModelSchema
);

module.exports = PushNotificationModel;
